### ISSUE TITLE
重复轮子

### ISSUE THREAD

**Issue by alex3236** [Ivan-1F/CarpetTick#1]
你完全可以通过 Carpet 的 `/profile` 达成对应功能。
即使不能，MCDR 也并不适合做这类功能。
MCDR 插件无法实现客户端自动补全，这使其使用体验非常糟糕。

**Comment by Ivan-1F** [comment]
README 已更新，这个插件是为 1.13 服务器设计的，carpet 1.13 没有 `/profile`

`!!tick h` 和 `!!tick e` 不是需要频繁调用的功能，即使没有自动补全使用体验也不会很差

**Comment by alex3236** [comment]
明白了（怪
